### ISSUE TITLE
I still don't get the joke here

### ISSUE THREAD

**Issue by zurgeg** [6200m/gloomarkov#1]
I've looked at the code for quite a long time and I still don't get the joke.

**Comment by 2secslater** [comment]
It's the best thing you've ever seen.
You cannot tell the difference between [this](https://github.com/6200m/gloomarkov/files/5745413/out.txt) and 6100m's real messages, it's that good.

**Comment by ghost** [comment]
This is stalking actually. Im not ok with this and i and many others dont find this funny nor get the joke
